### ISSUE TITLE
Not initialized

### ISSUE THREAD

**Issue by C00Lzero** [nealwon/go-flutter-plugin-sqlite#1]
Hi, 
i'm not sure, if this plugin is working, 
unfortionately i get the following errer: 
`cmd/main.go:34:21: cannot take the address of sqflite.NewSqflitePlugin("x", "y")`

`cmd/main.go:34:21: cannot use &sqflite.NewSqflitePlugin("x", "y") (type **sqflite.SqflitePlugin) as type flutter.Plugin in argument to flutter.AddPlugin:
	**sqflite.SqflitePlugin does not implement flutter.Plugin (missing InitPlugin method)`

I hope you can help me here, since this is really something i need

**Comment by nealwon** [comment]
I tested right now, it works.

I think maybe you need to check the repo revision you used in your go.mod.

plz give more informations. Thx!

**Comment by nealwon** [comment]
Okay! 
I knew what happened!

Wrong usage example in my readme file! (I've updated it)
Sorry!
