### ISSUE TITLE
add example

### ISSUE THREAD

**Issue by ghost** [nealwon/go-flutter-plugin-sqlite#2]
Looks good.

Can you add a basic example.

Here is a good one that does the same as yours to get started if it helps.
https://github.com/synw/sqlcool/blob/master/pubspec.yaml#L22
https://github.com/synw/sqlcool

**Comment by nealwon** [comment]
This is an implementation of flutter's sqflite plugin  for the desktop version. The full example usage can be found here https://pub.dartlang.org/packages/sqflite#-readme-tab-

**Comment by ghost** [comment]
thanks @nealwon 

This is the first go-flutter plugin i have seen. I can now now how easy it is to make others.
I am going about to make a Printer plugin also if you interested- let me knwo

**Comment by nealwon** [comment]
I don’t have enough experience with Printer development. Thanks!
