### ISSUE TITLE
Where Sqlite file is located of the application.

### ISSUE THREAD

**Issue by maheshbhattaraai** [nealwon/go-flutter-plugin-sqlite#5]
> If we want to remigrate then how can we do that. How Can we find this database?

**Comment by maheshbhattaraai** [comment]
After using go flutter with sqflite plugin . How can we find this database file in  pc @Drakirus

**Comment by pchampio** [comment]
Everything is described [here](https://github.com/nealwon/go-flutter-plugin-sqlite/blob/abe0dc068a77e12194d4c8a11a02e2393ac6839c/plugin.go#L116-L134)
 - On linux: `~/config/XXXXX.db`
 - On macOS `~/Library/Application Support/XXXX.db`
 - On wnidows `C:\Users\AAAA\AppData\Roaming\XXXX.db`

NOTE: It might change in future release: https://github.com/nealwon/go-flutter-plugin-sqlite/pull/3

**Comment by maheshbhattaraai** [comment]
Thanks a lot @Drakirus
